In [2]:
import pandas as pd

In [3]:
cle_train = pd.read_csv('Archive/cle_metadata_cnn_train.csv')
cle_test = pd.read_csv('Archive/cle_metadata_cnn_test.csv')

In [4]:
cle_test

,0,1,2,3,4,5,6,7,8,9,...,7.3,8.3,9.3,10.3,11.3,12.3,13.3,14.3,15.3,num
0,0.0,1.576204,0.425418,0.000000,0.268724,0.449675,1.255515,0.017467,0.127063,0.0,...,1.911400,0.0,0.0,1.368489,0.0,0.0,0.0,0.0,2.352829,0.50
1,0.0,2.096074,0.112876,0.000000,0.143072,0.053330,1.652721,0.000000,0.000000,0.0,...,2.105828,0.0,0.0,1.484470,0.0,0.0,0.0,0.0,2.614805,0.75
2,0.0,0.410527,1.482395,1.029471,1.204768,1.621189,0.422033,1.139812,1.480421,0.0,...,1.868459,0.0,0.0,1.335911,0.0,0.0,0.0,0.0,2.338708,0.00
3,0.0,2.235174,0.074740,0.000000,0.079568,0.072115,1.834668,0.000000,0.000000,0.0,...,1.904524,0.0,0.0,1.347446,0.0,0.0,0.0,0.0,2.325828,0.75
4,0.0,0.243156,1.304830,0.914779,1.077529,1.312706,0.370080,0.972016,1.398930,0.0,...,1.775253,0.0,0.0,1.236982,0.0,0.0,0.0,0.0,2.224280,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.0,1.948731,0.235453,0.000000,0.256912,0.299599,1.552018,0.000000,0.000000,0.0,...,2.111128,0.0,0.0,1.477408,0.0,0.0,0.0,0.0,2.628586,0.25
96,0.0,1.183947,0.824110,0.005812,0.678058,0.832374,0.938337,0.134900,0.365185,0.0,...,1.797031,0.0,0.0,1.295662,0.0,0.0,0.0,0.0,2.208438,0.00
97,0.0,0.247712,1.418063,0.860715,1.220798,1.408600,0.251707,0.984576,1.322066,0.0,...,1.655237,0.0,0.0,1.153829,0.0,0.0,0.0,0.0,2.091654,0.00
98,0.0,0.532114,1.298319,0.852904,1.097873,1.443981,0.529050,1.027145,1.294246,0.0,...,1.789982,0.0,0.0,1.277752,0.0,0.0,0.0,0.0,2.233064,0.00
99,0.0,0.398069,1.468871,0.998000,1.219631,1.619443,0.420176,1.156922,1.466599,0.0,...,1.818395,0.0,0.0,1.299711,0.0,0.0,0.0,0.0,2.276968,0.00

In [5]:
cle_test.iloc[9]

cp_1.0         0.000000
cp_2.0         0.000000
cp_3.0         0.000000
cp_4.0         1.000000
restecg_0.0    1.000000
restecg_1.0    0.000000
restecg_2.0    0.000000
slope_1.0      0.000000
slope_2.0      1.000000
slope_3.0      0.000000
thal_3.0       1.000000
thal_6.0       0.000000
thal_7.0       0.000000
age            0.708333
sex            0.000000
trestbps       0.132075
chol           0.326484
fbs            0.000000
thalach        0.748092
exang          1.000000
oldpeak        0.290323
ca             0.666667
num            0.250000
Name: 9, dtype: float64